pipeline:
    name: Remote1
    identifier: Remote1
    projectIdentifier: KD_Test
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Approval
              identifier: Approval
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: Approver
                                identifier: Approver
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups:
                                            - account.KD
                                    approverInputs: []
              tags: {}
